[build-system]
requires = ["setuptools"]

[project]
name = "project-pycliapp"
version = "0.1.0"
dependencies = [
    "colorama",
    "pyfiglet",
]

[project.scripts]
abot = "main:main"
abot-dev = "main:dev_main"